# my-webapp-chart/templates/backend-service.yaml
{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Service
metadata:
  name: {{ include "hello-chart.fullname" . }}-backend
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend # Helm-specific label
    app: hello-app # Your original label
    tier: backend # Your original label
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    {{- include "hello-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend # Helm-specific label
    app: hello-app # Your original label
    tier: backend # Your original label
{{- end }}
