# my-webapp-chart/templates/frontend-service.yaml
{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Service
metadata:
  name: {{ include "hello-chart.fullname" . }}-frontend
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend # Helm-specific label
    app: frontend # Your original label
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    {{- include "hello-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend # Helm-specific label
    app: frontend # Your original label
{{- end }}
