# k8s-manifests/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service # This name will be used for internal DNS resolution (e.g., http://backend-service:5000)
  labels:
    app: hello-app
    tier: backend
spec:
  selector:
    app: hello-app
    tier: backend
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000 
  type: LoadBalancer
   
