apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: hello-app
    tier: backend # <--- ADDED THIS LABEL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
      tier: backend # <--- ADDED THIS LABEL TO MATCH SERVICE SELECTOR
  template:
    metadata:
      labels:
        app: hello-app
        tier: backend # <--- ADDED THIS LABEL TO THE PODS
    spec:
      containers:
      - name: backend
        image: gcr.io/eighth-beacon-466412-f3/backend@sha256:116150997838dd10101d77339739154b71b1a5966a665cf445495cca94c4a485
        ports:
        - containerPort: 5000
        resources:
          requests:
            # Add your resource requests here, e.g.:
            # cpu: "100m"
            # memory: "128Mi"
