apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1 # You can increase this
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/eighth-beacon-466412-f3/frontend@sha256:ecb0da7add5d0bfd609dae7da2133957f366bd650efbde1ebb3d68ab1520beba # Replace with your image
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
